name: Deploy to AWS EC2
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"
      # 프론트엔드 빌드
      - name: Install dependencies
        working-directory: frontend
        run: |
          npm ci
          npm install @rollup/rollup-linux-x64-gnu rollup --force

      - name: Build project
        working-directory: frontend
        run: npm run build

      # 빌드 결과물 압축
      - name: Create deployment archive
        run: tar -czf dist.tar.gz -C frontend/dist .

      # 빌드 결과물 저장
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist.tar.gz

  deploy:
    needs: build # build 작업 완료 후 실행
    runs-on: ubuntu-latest
    steps:
      # 빌드 결과물 다운로드
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files

      # EC2에 배포
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          # 빌드 파일 전송
          scp -o StrictHostKeyChecking=no -i private_key dist.tar.gz ${USER}@${HOST}:/home/${USER}

          # SSH 접속 및 배포 명령 실행
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << 'EOF'
            # 프로젝트 디렉토리로 이동
            cd /home/${USER}

            # 기존 빌드 백업
            if [ -d "dist" ]; then
              mv dist dist_backup_$(date +%Y%m%d_%H%M%S)
            fi

            # 새 빌드 파일 압축 해제
            mkdir -p dist
            tar -xzf dist.tar.gz -C dist

            # Apache 재시작
            sudo systemctl restart apache2
          EOF
